### ISSUE TITLE
部署完成访问显示file not found

### ISSUE THREAD

**Issue by zhzhzhy** [dunmengjun/my-subconverter#2]
按照步骤部署的，好像是 和https://github.com/tindy2013/subconverter/issues/266
类似的问题，与docker version有关，麻烦更新一下，谢谢

**Comment by dunmengjun** [comment]
@zhzhzhy 你的意思是说，部署已经完成了，但是按照subconverter文档中规定的的url去访问的时候，返回file not found吗？如果是这样的话，你的url方便发出来吗？可以把前面的endpoint(部署完成okteto自动给你生成的域名)给遮住或者截掉，方便我看看是啥问题，因为我自己这边都是好的，三个月了也没变过，我就是按照subconverter文档中给的参数去访问的，没有加version啥的

**Comment by zhzhzhy** [comment]
![Screenshot_20210211-143805_Chrome~2](https://user-images.githubusercontent.com/36782632/107608599-62d58300-6c77-11eb-9d85-46cf4ba59f65.png)
![Screenshot_20210211-144102_Chrome](https://user-images.githubusercontent.com/36782632/107608604-69fc9100-6c77-11eb-86ec-59b00fc3fffe.png)

如图，部署完成访问网站，只要file not found，访问你现在repo提供的的url也是同样的问题

**Comment by dunmengjun** [comment]
@zhzhzhy 我手贱给你把两个截图都删除了😂，没事，你的问题我知道出在哪儿了，给你解释一下哈，subconverter只是一个转译服务器，就clash来说 subconverter只负责把你的机场的clash文件内容按照你设定的一些规则给处理一下然后提供成另外一个clash文件，在操作上来说就是，你部署完了之后，需要访问这样的url 

https://{你的okteto域名}/sub?target=clash&url={你的机场提供的clash文件的url(base64加密)}&include=xxx 

当你访问上诉url的时候，subconverter先去你的机场把原始clash文件拿过来，然后按照你设定的规则，比如上面url的规则是include,代表只保留包含xxx字符的代理。

上述内容都可以参考subconverter的文档 [https://github.com/tindy2013/subconverter/blob/master/README-cn.md](subconverter中文文档)

所以在用这个工程部署完成subconverter服务器之后，其实只代表服务器部署好了，你还需要参考subconverter的文档还有自己的需求来配置你自己的url。

希望上诉解释可以帮助到你😀

**Comment by zhzhzhy** [comment]
@dunmengjun ，谢谢大佬指点😂，文档能详细点就更好了，我以为这是带有前端页面的subconverter,要是能够通过类似https://bianyuan.xyz/这个带前端复制粘贴的就能方便很多

**Comment by dunmengjun** [comment]
@zhzhzhy 看了下你给的这个url，应该是一个以subconverter为后端的前端工程。我会在我repo的文档上标明我这只是subconverter后端的部署工程的，还会加链接指向subconverter用法文档，谢谢提醒。然后有时间我也会把你提的那个前端工程也部署到云上去，到时候再更新这个issue。

**Comment by lin-z-z** [comment]
请问下楼主，这个https://{你的okteto域名}/sub?target=clash&url={你的机场提供的clash文件的url(base64加密)}&include=xxx，应该怎么填充呢，我的机场提供的clash文件的url也是加密的，但是我每次请求都是400 Bad Request
